config/routes.rb
HolidayplannerV3::Application.routes.draw do
  

  

  scope "/(:localization)", :localization => /default|pl|en|ir|it/ do
    match "planner/(:year)" => "planner#show", :as => :planner
    match "leave_request" => "leave_requests#show", :as => :leave_request
  end

  
  match "/posts" => "posts#index"
  match "/posts/:permalink" => "posts#show", :as => :post

  namespace :admin do
    resources :custom_pages
    resources :posts
  end

  get "/:permalink" => "custom_pages#show"

  root :to => "planner#show", :localization => 'default'

end

app/controllers/planner_controller.rb
class PlannerController < ApplicationController

  before_filter :get_year
  before_filter :get_localization
  
  #
  # Main planner action, shows calendar planner
  #
  def show
    @public_holidays = get_public_holidays( @year )
    if request.xhr?
      render :partial => "calendar", :locals => { :year => @year, :localization => @localization, :public_holidays => @public_holidays }
    else
      respond_to do |format|
        format.html
        format.xml
        format.json
      end
    end
  end

protected

  #
  # returns year sent in request or current year
  #
  def get_year
    @year ||= params[:year] ? params[:year].to_i : Time.now.year
  end

  #
  # returns public holidays depending on current locale
  #
  def get_public_holidays( year )
    PublicHoliday.factory( @localization ).all( year )  
  end

end

app/helpers/planner_helper.rb
module PlannerHelper

  def week_day_class( date )
    dm = []
    dm << "last-day-of-month" if date.end_of_month == date 
    dm << "first-day-of-month" if date.day == 1 
    case date.cwday
      when 7
        dm = dm + ["sunday", "weekend"]
      when 6
        dm = dm + ["saturday", "weekend"]
    end
    dm.join(" ")
  end

  def clickable_day_class( date, public_holidays )
    if ![7,6].include?( date.cwday ) && !is_holiday?( date, public_holidays )
      "clickable"
    end
  end

  def is_holiday?( date, public_holidays )
    public_holidays.collect( &:date ).include? date
  end

  def get_holiday( date, public_holidays )
    public_holidays.select{ |h| h.date == date }.first
  end

  def calendar_day_cell( date, public_holidays )
    desc = is_holiday?( date, public_holidays ) ? t( get_holiday( date, public_holidays ).code ) : ""
    a_class = [ 
      "day", 
      week_day_class(date), 
      is_holiday?( date, public_holidays ) ? "holiday" : nil, 
      clickable_day_class( date, public_holidays ),
      date.today? ? 'today' : nil 
    ].compact.join(' ')
    link = content_tag( :a, date.day, :class => a_class, :id => date, :title => desc, :href => "#" )
    content_tag :td, link
  end

end

app/views/planner/_calendar.html.erb
<% cache "#{I18n.locale}/#{localization}/#{year}", :expires_in => 5.hours do %>
  <div class="calendar-element">
    <div class="tab_container">
      <section id="tab1" class="tab_content">
        <div class="info-bar">
          <span class="counts-wrapper">
            <%=t 'portal.you_have_planned' %> <span id="leave-count" class="count">0</span> 
            <%=t 'portal.days_of_leave' %> - <%=t 'portal.got' %>
            <span id="period-count" class="count">0</span> <%=t 'portal.days_of' %>!
          </span>
          <span id="save-info"></span>
        </div>
      
        <section class="calendar-wrapper">
          <table class="calendar" cellspacing="0" cellpadding="0">
            <tbody>
              <% (1..12).each do |month| %>
                <%= render :partial => "calendar_month", :locals => { :month => month, :public_holidays => public_holidays } %>
              <% end %>
            </tbody>
          </table>
        </section>
      </section>
      
      <section id="tab2" class="tab_content">
        <%= render :partial => "list", :locals => { :public_holidays => public_holidays } %>
      </section>
  
      <section id="tab3" class="tab_content">
        <%= render :partial => "leave_requests/index" %>
      </section>
    </div>
  </div>
<% end %>

app/views/planner/_calendar_month.html.erb
<% date = Date.civil(@year, month, 1) %>

<tr class="day-of-week-names">
  <td></td>

  <% unless date.cwday == 1 %>
    <% (1...(date.cwday)).to_a.reverse.each do |fill| %><td></td><% end %>
  <% end %>

  <% while date.month == month do %>
    <%= content_tag :td, l(date, :format => "%a") %>
    <% date = date + 1.day %>
  <% end %>
</tr>

<% date = Date.civil(@year, month, 1) %>
<tr class="month<%= month %>">
    
  <td class="month-name">
    <%= content_tag :div, h(I18n.l date, :format => "%B"), :class => "month-name-label" %>
  </td>

  <% unless date.cwday == 1 %>
    <% (1...(date.cwday)).to_a.reverse.each do |fill| %>
      <%= content_tag :td, content_tag( :div, "", :class => ["fill", week_day_class(date-fill.day)].compact.join(' ') )%>
    <% end %>
  <% end %>
            
  <% while date.month == month do %>
    <%= calendar_day_cell( date, public_holidays ) %>
    <% date = date + 1.day %>
  <% end %>
              
</tr>

app/views/planner/_list.html.erb
<% public_holidays.sort_by{|d| d.date }.group_by{|d| d.date.month }.each do |month, holidays_by_month| %>

  <div class="holidays-list-month-container">
    <table>
      <tr>
        <td class="holidays-list-month">
          <div class="holidays-list-month-name"><%=l holidays_by_month.first.date, :format => "%m" %></div>
        </td>
        <td>
            <ul class="holidays-list">
              <% holidays_by_month.each do |day| %>
                <li>
                  <span class="holidays-list-date"><%=l day.date %></span> <%=t day.code %>
                </li>
              <% end %>
            </ul>
        </td>
      </tr>
    </table>
  </div>

<% end %>

app/views/planner/show.html.erb
<% content_for :year_holder do %>
  <%= link_to image_tag('/images/prev.gif'), planner_path( params[:localization], @year - 1 ), :class => "x-year-change x-year-change-minus" %>
  <span class="x-year"><%=h @year %></span>
  <%= link_to image_tag('/images/next.gif'), planner_path( params[:localization], @year + 1 ), :class => "x-year-change x-year-change-plus" %>
<% end %>

<ul class="tabs">
  <li><a href="#tab1">Planner</a></li>
  <li><a href="#tab2"><%= t('portal.tabs.list').capitalize %></a></li>
  <% if LEAVE_REQUEST_PDF_LOCALIZATIONS.include?( @localization.to_sym ) %>
    <li><a href="#tab3" class="new"><%= t('portal.tabs.leave_request').capitalize %>!</a></li>
  <% end %>
</ul>

<div class="calendar-section section-swap-container">
  <%= render :partial => "calendar", :locals => { :year => @year, :localization => @localization, :public_holidays => @public_holidays } %>
</div>

app/views/planner/show.json.erb
{
  "info": { "localization": "<%= session[:localization] %>", "language": "<%= I18n.locale %>", "year": "<%= @year %>" },
  "public_holidays": [ 
  <% @public_holidays.each do |p| %> 
    { "date": "<%= p.date %>", "name": "<%= t( p.code ) %>", "code": "<%= p.code %>" }<%= ',' unless p == @public_holidays.last %> 
  <% end %> ]
}